version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.6.4
    steps:
      - checkout
      - restore_cache:
          key: deps9-{{ .Branch }}-{{ checksum "Pipfile.lock" }}
      - run:
          command: |
            sudo pip install pipenv
            pipenv install --dev --deploy
      - save_cache:
          key: deps9-{{ .Branch }}-{{ checksum "Pipfile.lock" }}
          paths:
            - ".venv"
      - run:
          command: |
            pipenv run flake8
          command: |
            cp website/settings.py.sample website/settings.py
            cat >>website/settings.py <<END
            TEST_RUNNER = 'xmlrunner.extra.djangotestrunner.XMLTestRunner'
            TEST_OUTPUT_VERBOSE = 2
            TEST_OUTPUT_DIR = 'test-results'
            END
            pipenv run "python manage.py test"
      - store_test_results:
          path: test-results
      - store_artifacts:
          path: test-results
destination: tr1
